# Generated by Django 3.2.16 on 2023-03-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='company',
            field=models.CharField(max_length=30),
        ),
    ]
